blueprint:
  name: "Zooz ZEN32 Scene Controller: Scene Control"
  description: >
    Link a Zooz ZEN32 Scene Controller button to a specific scene.


    Due to HomeAssistant limitations with scenes, an enity must be picked to show status
    of the scene. The best choice is to create a group that contains all the entities
    in the scene and use that.


    Press button **once** to toggle scene, **double-tap** to set to max brightness for 
    the monitored entity/group, **hold** to turn off the monitored entity/group.
    

  domain: automation
  input:
    device_id:
      name: Zooz Switch
      description: List of available Zooz ZEN32 switches.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN32
    scene_button:
      name: Scene Button
      description: The button to link to light
      default: '001'
      selector:
        select:
          mode: dropdown
          options:
            - label: Scene 5 (Big Button)
              value: '005'
            - label: Scene 1 (Top Left)
              value: '001'
            - label: Scene 2 (Top Right)
              value: '002'
            - label: Scene 3 (Bottom Left)
              value: '003'
            - label: Scene 4 (Bottom Right)
              value: '004'

    scene_name:
      name: Scene
      description: Scene to activate on button press
      selector:
        entity:
          domain:
          - scene

    status_entity:
      name: Device for status
      description: |
        The group, light or switch to use as a status indicator.


        It is recommended to create a group that has the same members as the scene, but an individual entity
        can also be used.
      selector:
        entity:
          domain:
          - light
          - switch

    off_color:
      name: Off Color
      description: Color to make indicator when light is off (default white)
      default: '0'
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'
    dimmed_color:
      name: Dimmed Color
      description: Color to make indicator when light is dimmed (default blue)
      default: '1'
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'


mode: restart
max_exceeded: silent

variables:
  # minimum value to consider light as "full" brightness
  full_brightness: 250

  # constants from https://www.support.getzooz.com/kb/article/608-zen32-scene-controller-advanced-settings/
  led_always_off: 2
  led_always_on: 3
  
trigger:
  # controller trigger (set light)
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      command_class_name: Central Scene
      device_id: !input device_id

  # light state changed
  - platform: state
    entity_id: !input status_entity

  # used for initialization
  - platform: event
    event_type: automation_reloaded

action:
  - variables:
      scene_button: !input scene_button
      device_id: !input device_id
      status_entity: !input status_entity

      # from https://www.support.getzooz.com/kb/article/608-zen32-scene-controller-advanced-settings/
      led_indicator_mode_param: "{{ ((scene_button | int) % 5) + 1 }}" # '005' => 1, '001' => 2, '002' => 3, '003' => 4, '004' => 5
      led_indicator_color_param: "{{ ((scene_button | int) % 5) + 6 }}" # '005' => 6, '001' => 7, '002' => 8, '003' => 9, '004' => 10

  - choose:
      # controller
      - alias: Controller button pressed
        conditions: "{{ trigger.event.data.device_id == device_id and trigger.event.data.property_key_name == scene_button }}"
        sequence: 
          - choose:
              - alias: Controller button single press
                conditions: "{{ trigger.event.data.value == 'KeyPressed' }}"
                sequence:
                  - if:
                      - condition: template
                        value_template: "{{ states(status_entity) == 'on' }}"
                    then:
                      - service: light.turn_off
                        target: 
                          entity_id: !input status_entity
                      - service: switch.turn_off
                        target: 
                          entity_id: !input status_entity
                    else:
                      - service: scene.turn_on
                        target: 
                          entity_id: !input scene_name

              - alias: Controller button double press
                conditions: "{{ trigger.event.data.value == 'KeyPressed2x' }}"
                sequence:
                  - service: light.turn_on
                    data:
                      brightness_pct: 100
                    target: 
                      entity_id: !input status_entity
                  - service: switch.turn_on
                    target: 
                      entity_id: !input status_entity

              - alias: Controller button held
                conditions: "{{ trigger.event.data.value == 'KeyHeldDown' }}"
                sequence:
                  - service: light.turn_off
                    target: 
                      entity_id: !input status_entity
                  - service: switch.turn_off
                    target: 
                      entity_id: !input status_entity

      # light changed
      - alias: Light turned on/changed to less than full brightness
        conditions: "{{ trigger.entity_id == status_entity and trigger.to_state.state == 'on' and trigger.to_state.brightness < full_brightness }}"
        sequence:
          - parallel: 
              - alias: Set ZEN32 indicator LED color
                service: zwave_js.set_config_parameter 
                data:
                  parameter: "{{ led_indicator_color_param }}"
                  value: !input dimmed_color
                target: 
                  device_id: !input device_id
              - alias: Turn on ZEN32 indicator LED
                service: zwave_js.set_config_parameter 
                data:
                  parameter: "{{ led_indicator_mode_param }}"
                  value: "{{ led_always_on }}"
                target: 
                  device_id: !input device_id
      - alias: Light turned on/changed to full brightness
        conditions: "{{ trigger.entity_id == status_entity and trigger.to_state.state == 'on' }}"
        sequence: 
          - alias: Turn off ZEN32 indicator LED
            service: zwave_js.set_config_parameter 
            data:
              parameter: "{{ led_indicator_mode_param }}"
              value: "{{ led_always_off }}"
            target: 
              device_id: !input device_id
      - alias: Light turned off
        conditions: "{{ trigger.entity_id == status_entity and trigger.to_state.state == 'off' }}"
        sequence:
          - parallel: 
              - alias: Set ZEN32 indicator LED color
                service: zwave_js.set_config_parameter 
                data:
                  parameter: "{{ led_indicator_color_param }}"
                  value: !input off_color
                target: 
                  device_id: !input device_id
              - alias: Turn on ZEN32 indicator LED
                service: zwave_js.set_config_parameter 
                data:
                  parameter: "{{ led_indicator_mode_param }}"
                  value: "{{ led_always_on }}"
                target: 
                  device_id: !input device_id
