blueprint:
  name: Z-Wave Plus 700 Series S2 Dimmer Switch (Zen77)
  description: Create automations for the Z-Wave Plus 700 Series S2 Dimmer Switch
    using the ZWave-JS integration.
  domain: automation
  input:
    zooz-switch:
      name: Zen77 Dimmer
      description: List of available Zen77 dimmers.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN77
          multiple: false
    button_a:
      name: Button A - Up/On press 1x
      description: Action to run, when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_a2:
      name: Button A - Up/On press 2x
      description: Action to run, when the button is pressed two times.
      default: []
      selector:
        action: {}
    button_a4:
      name: Button A - Up/On press 4x
      description: Action to run, when the button is pressed four times.
      default: []
      selector:
        action: {}
    button_a5:
      name: Button A - Up/On press 5x
      description: Action to run, when the button is pressed five times.
      default: []
      selector:
        action: {}
    button_a_held:
      name: Button A - Up/On held down
      description: Action to run, when the button is held down.
      default: []
      selector:
        action: {}
    button_b:
      name: Button B - Down/Off press 1x
      description: Action to run, when the button is pressed one time.
      default: []
      selector:
        action: {}
    button_b2:
      name: Button B - Down/Off press 2x
      description: Action to run, when the button is pressed two times.
      default: []
      selector:
        action: {}
    button_b4:
      name: Button B - Down/Off press 4x
      description: Action to run, when the button is pressed four times.
      default: []
      selector:
        action: {}
    button_b5:
      name: Button B - Down/Off press 5x
      description: Action to run, when the button is pressed five times.
      default: []
      selector:
        action: {}
    button_b_held:
      name: Button B - Down/Off held down
      description: Action to run, when the button is held down.
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/z-wave-plus-700-series-s2-dimmer-switch-zen77-blueprint/414382
mode: single
max_exceeded: silent
variables:
  device_id: !input zooz-switch
trigger:
- platform: event
  event_type: zwave_js_value_notification
condition: '{{ trigger.event.data.device_id == device_id }}'
action:
- variables:
    button_id: '{{ trigger.event.data.property_key_name }}'
    press_count: '{{ trigger.event.data.value }}'
- service: logbook.log
  data:
    name: Button Id
    message: '{{ button_id }}'
- service: logbook.log
  data:
    name: Press Count
    message: '{{ press_count }}'
- choose:
  - conditions: '{{ button_id == "001" and press_count == "KeyPressed" }}'
    sequence: !input button_a
  - conditions: '{{ button_id == "001" and press_count == "KeyPressed2x" }}'
    sequence: !input button_a2
  - conditions: '{{ button_id == "001" and press_count == "KeyPressed4x" }}'
    sequence: !input button_a4
  - conditions: '{{ button_id == "001" and press_count == "KeyPressed5x" }}'
    sequence: !input button_a5
  - conditions: '{{ button_id == "001" and press_count == "KeyHeldDown" }}'
    sequence: !input button_a_held
  - conditions: '{{ button_id == "002" and press_count == "KeyPressed" }}'
    sequence: !input button_b
  - conditions: '{{ button_id == "002" and press_count == "KeyPressed2x" }}'
    sequence: !input button_b2
  - conditions: '{{ button_id == "002" and press_count == "KeyPressed4x" }}'
    sequence: !input button_b4
  - conditions: '{{ button_id == "002" and press_count == "KeyPressed5x" }}'
    sequence: !input button_b5
  - conditions: '{{ button_id == "002" and press_count == "KeyHeldDown" }}'
    sequence: !input button_b_held
